#! /bin/bash

WAIT_HOST=$(eval echo \${$1})
WAIT_PORT=$(eval echo \${$2})

echo -n "Waiting for service at $WAIT_HOST:$WAIT_PORT"

until echo dummy-value 2>/dev/null | nc $WAIT_HOST $WAIT_PORT >/dev/null 2>&1; do
    echo -n "."
    sleep 1
done

echo
